name: 'Create Namespace'
description: 'Create a kubernetes namespace'
author: 'local-ch'
inputs:
  namespace:
    description: 'The name of the namespace that shall be created'
    required: true
  guild:
    description: 'The name of the guild to create a namespace for [web/nodejs]'
    required: true
    default: 'nodejs'
outputs:
  name:
    description: 'The name of the namespace that was created'

runs:
  using: 'node12'
  main: 'dist/index.js'
